BookFair/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView
from . import views

urlpatterns = [
    # Home page
    path("", views.home, name="home"),
    # Category page
    path("category/<int:cat_id>/", views.category, name="category"),
    # Product page
    path("product/<int:prod_id>/", views.product, name="product"),

    # path('user-profile/', user_profile, name='user_profile'),
    
    # Login page
    path('login/', views.CustomerLoginView.as_view(template_name="BookFair/login.html"), name='login'),
    # Signup/registration page
    path('signup/', views.SignupView.as_view(), name='signup'),
    # Profile details
    path('profile/', views.profile, name='profile'),
    # Log out page
    path('logout/', views.LogoutView, name='logout'),
    # Search page
    path('search/', views.search, name='search')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # Warning: this will not work outside of debug mode!
# See: https://docs.djangoproject.com/en/4.2/howto/static-files/ and https://docs.djangoproject.com/en/4.2/howto/static-files/deployment/

eBook/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("BookFair.urls"))
    # path("BookFair/", include("BookFair.urls"))
]

BookFair/forms.py
from django import forms
from django.contrib.auth.password_validation import validate_password
from django.core.validators import validate_email
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from BookFair.models import Customer

class SearchBoxNav(forms.Form):
    q = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control bg-primary-subtle text-emphasis',
                'type': 'search',
                'placeholder': 'Search',
                'aria-label': 'Search'
            }
        )
    )

class SearchBoxFull(forms.Form):
    q = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control bg-primary text-emphasis',
                'type': 'search',
                'aria-label': 'Search'
            }
        ),
        label=""
    )
    sort = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                'class': 'btn bg-primary-subtle text-light dropdown-toggle',
                'type': 'button',
                'data-bs-toggle': 'dropdown',
                'aria-expanded': 'false'
            }
        ),
        choices = [
            ("name", "Name"),
            ("price-lh", "Price, low to high"),
            ("price-hl", "Price, high to low"),
            ("stock-lh", "In stock, low to high"),
            ("stock-hl", "In stock, high to low")
        ],
        label = "Sort by:"
    )

class CustomerSignupForm(forms.Form):
    prefix = "signup"

    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type': 'text'
            }
        ),
        label = "Username"
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'type': 'password'
            }
        ),
        label = "Password",
        validators = [validate_password]
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'type': 'password'
            }
        ),
        label = "Retype password",
        validators = [validate_password]
    )
    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type': 'text'
            }
        ),
        label = "First name",
        max_length = 45
    )
    last_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type': 'text'
            }
        ),
        label = "Last name",
        max_length = 45
    )
    email = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type': 'email',
                'placeholder': 'myaddress@example.com'
            }
        ),
        label = "Email",
        validators = [validate_email],
        max_length = 128
    )
    initial_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type': 'text',
            }
        ),
        label = "Initial",
        max_length = 1
    )
    phone_country = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type': 'text',
            }
        ),
        label = "Country prefix",
        max_length = 3
    )
    phone_number = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type': 'text',
            }
        ),
        label = "Phone number",
        max_length = 12
    )


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type': 'text'
            }
        ),
        label="Username"
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'type': 'password'
            }
        ),
        label="Password"
    )

BookFair/views.py
# Django packages
from django.shortcuts import render, HttpResponse, get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.views import LoginView
from django.contrib.auth.models import User
from django.contrib import messages
from django.db import transaction
from django.db.models import Q
from django.urls import reverse
from django.views.generic.edit import FormView

# Model packages
from BookFair.models import Customer, Category, Product#,  Cart, UserProfile
# Form packages
from BookFair.forms import SearchBoxNav, SearchBoxFull, CustomerSignupForm, LoginForm
# Python packages
import random
from functools import reduce
import operator
# Logger
import logging

# Create your views here.
def home(request):
    # Get 4 random object IDs
    num_products = Product.objects.count()
    rand_product_ids = random.sample(range(1,num_products), 4)
    # Get corresponding product objects
    rand_product_objs = [Product.objects.get(pk=prod_id) for prod_id in rand_product_ids]

    return render(request, "BookFair/home.html", {"featured_products": rand_product_objs})

def category(request, cat_id):
    req_category = get_object_or_404(Category, pk=cat_id)

    cat_products = req_category.product_set

    # Sorting options
    match request.GET.get('sort'):
        case "name":
            cat_products_sorted = cat_products.order_by('prod_name')
        case "price-lh":
            cat_products_sorted = cat_products.order_by('prod_price')
        case "price-hl":
            cat_products_sorted = cat_products.order_by('-prod_price')
        case "stock-lh":
            cat_products_sorted = cat_products.order_by('prod_stock')
        case "stock-hl":
            cat_products_sorted = cat_products.order_by('-prod_stock')
        case _:
            cat_products_sorted = cat_products.order_by('prod_name').all()

    return render(request, "BookFair/category.html", {"category": req_category, "cat_products": cat_products_sorted})

def product(request, prod_id):
    req_product = get_object_or_404(Product, pk=prod_id)

    return render(request, "BookFair/product.html", {"product": req_product})

# def add_to_cart(request, prod_id):
#     product = get_object_or_404(Product, pk=prod_id)
#     user_profile = UserProfile.objects.get(user=request.user)

#     # Check if the user has an existing cart
#     if not hasattr(user_profile, 'cart'):
#         cart = Cart.objects.create(user_profile=user_profile)
#         user_profile.cart = cart
#         user_profile.save()

#     # Add the product to the cart
#     user_profile.cart.products.add(product)
#     messages.success(request, 'Product added to cart!')
#     return redirect('user_profile')


# def view_cart(request):
#     user_profile = UserProfile.objects.get(user=request.user)
#     cart = user_profile.cart
#     cart_products = cart.products.all()
#     return render(request, 'BookFair/view_cart.html', {'cart_products': cart_products})

def profile(request):
    # Get customer that corresponds to signed-in user
    cur_user = request.user
    # Initialize cur_customer to none
    cur_customer = None

    if (cur_user is not None) & (cur_user.is_authenticated):
        cur_customer = Customer.objects.get(user=cur_user)

    return render(request, 'BookFair/profile.html', {'customer': cur_customer})

def LogoutView(request):
    # Simple logout page
    logout(request)

    return render(request, 'BookFair/logout.html')

class SignupView(FormView):
    template_name = "BookFair/signup.html"
    form_class = CustomerSignupForm

    def get_success_url(self):
        return reverse(profile)

    def post(self, request, *args, **kwargs):
        # Get form object to validate
        form = self.get_form()
        if form.is_valid():
            # Check that password is the same -- form validation does not help here
            if form.cleaned_data['password1'] == form.cleaned_data['password2']:
                messages.success(request, "Successfully signed up!")
                return self.form_valid(form)
            else:
                messages.error(request, "Invalid password.")
                return self.form_invalid(form)

        return self.form_invalid(form)

    # A function that actually creates a user (and the corresponding customer) objects
    @transaction.atomic
    def create_user_transact(self, form):
        user = User.objects.create_user(
            form.cleaned_data['username'],
            form.cleaned_data['email'],
            form.cleaned_data['password1']
        )
        Customer.objects.create(
            user = user,
            cus_lname = form.cleaned_data['last_name'],
            cus_fname = form.cleaned_data['first_name'],
            cus_initial = form.cleaned_data['initial_name'],
            cus_email = form.cleaned_data['email'],
            cus_phone = form.cleaned_data['phone_number'],
            cus_phone_country = form.cleaned_data['phone_country']
        ).save()

        return user

    # A function that is called once the form has been checked for validity.
    def form_valid(self, form):
        self.create_user_transact(form)
        
        user = authenticate(
            username = form.cleaned_data['username'],
            password = form.cleaned_data['password1']
        )
        
        login(self.request, user)

        return super().form_valid(form)

# Login
class CustomerLoginView(LoginView):

    form_class = LoginForm
    template_name = "BookFair/login.html"

    def get_success_url(self):
        return reverse(profile)

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            messages.error(request, "Invalid login. Check your username and password.")
            return self.form_invalid(form)


# Search
def search(request):
    # The search query is to be submitted as a GET request
    search_form_full = SearchBoxFull()
    # Initialize query, query_results to none
    query = None
    query_results_sorted = None

    # Get the query in the GET request
    if request.GET.get('q'):
        # Make a form object and include the data in the request for validation
        ## First attempt it with SearchBoxFull (also setting search_form_full to fill it in w/ user value)
        search_form = search_form_full = SearchBoxFull(request.GET)
        ## Check if the form is not valid -- if it isn't, update it to check the nav form submission
        if not search_form.is_valid():
            search_form = SearchBoxNav(request.GET)
        ## Finally, if the form is valid on either try, get its query; if it's not, log an error.
        if search_form.is_valid():
            query = search_form.cleaned_data['q']

            # Separate query into tokens for word-by-word matching -- inspired by https://stackoverflow.com/questions/28278150/mysql-efficient-search-with-partial-word-match-and-relevancy-score-fulltext
            query_tokens = query.split()

            query_results = Product.objects.filter(
                # Q(prod_name__icontains = token)
                reduce(operator.or_, [Q(prod_name__icontains = token) for token in query_tokens])
                |
                reduce(operator.or_, [Q(prod_descript__icontains = token) for token in query_tokens])
                # Q(prod_descript__icontains = query)
            )

            # Sort time
            # Try to get sort -- if it's not in the POST request, just order it by name
            try:
                sort = search_form.cleaned_data['sort']

                match sort:
                    case "name":
                        query_results_sorted = query_results.order_by('prod_name')
                    case "price-lh":
                        query_results_sorted = query_results.order_by('prod_price')
                    case "price-hl":
                        query_results_sorted = query_results.order_by('-prod_price')
                    case "stock-lh":
                        query_results_sorted = query_results.order_by('prod_stock')
                    case "stock-hl":
                        query_results_sorted = query_results.order_by('-prod_stock')
                    case _:
                        query_results_sorted = query_results.order_by('prod_name')
            except KeyError:
                query_results_sorted = query_results.order_by('prod_name')
        else:
            logging.error('Invalid search form!')
    else:
        logging.error('No search query given!')

    return render(request, "BookFair/search.html", {'search_form': search_form_full, 'search_results': query_results_sorted, 'query': query})

BookFair/templates/BookFair/category.html
{% extends "base.html" %}
<!-- Title -->
{% block title %} eBookFair | {{ category.cat_name }} items {% endblock %}
<!-- Load django apps -->
{% load static %}
{% load bootstrap5 %}
<!-- Start block -->
{% block content %}
<!-- Product CSS -->
<link rel="stylesheet" type="text/css" href="{% static 'BookFair/css/product.css' %}">
<!-- Product listing -->
<div class="container d-flex align-items-end justify-content-between">
    <h1 class="mt-3 mb-0">
        {{ category.cat_name }} items
    </h1>
    <div class="dropdown">
        <button class="btn bg-primary-subtle text-light dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          Sort by
        </button>
        <ul class="dropdown-menu">
          <li><a class="dropdown-item" href="{% url 'category' category.cat_id %}?sort=name">Name</a></li>
          <li><a class="dropdown-item" href="{% url 'category' category.cat_id %}?sort=price-lh">Price, low to high</a></li>
          <li><a class="dropdown-item" href="{% url 'category' category.cat_id %}?sort=price-hl">Price, high to low</a></li>
          <li><a class="dropdown-item" href="{% url 'category' category.cat_id %}?sort=stock-lh">In stock, low to high</a></li>
          <li><a class="dropdown-item" href="{% url 'category' category.cat_id %}?sort=stock-hl">In stock, high to low</a></li>
        </ul>
      </div>
</div>
<hr>
<div class="container mb-5">
    <div class="row g-3">
        {% if cat_products %}
            {% for product in cat_products %}
                <div class="col-6 col-md-4 col-lg-3">
                    <div class="card">
                        <a href="{% url 'product' product.prod_id %}">
                            {% if product.prod_img %}
                                <img class="card-img-top" src="{{ product.prod_img.url }}">
                            {% else %}
                                <img class="card-img-top" src="{% static 'BookFair/img/product/placeholder.webp' %}">
                            {% endif %}
                            <div class="card-body">
                                <p class="fs-3 mb-0 lh-sm">{{ product.prod_name }}</p>
                                <p class="fs-5">${{ product.prod_price }}</p>
                            </div>
                        </a>
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    </div>
</div>
{% endblock %}

BookFair/templates/BookFair/home.html
{% extends "base.html" %}
<!-- Title -->
{% block title %} Welcome to the eBookFair! {% endblock %}
<!-- Load django apps -->
{% load static %}
{% load bootstrap5 %}

<!-- Content is loaded directly to webpage past this point -->
{% block content %}
<!-- Product CSS -->
<link rel="stylesheet" type="text/css" href="{% static 'BookFair/css/product.css' %}">

<!-- Hero image -->
<img class="img-fluid" src="{% static 'BookFair/img/home/hero.webp' %}">
<!--  -->
<hr>
<!-- Product stuff -->
<h1 class="mb-3">Featured products</h1>
<div class="container mb-5">
    <div class="row g-3">
        {% if featured_products %}
            {% for product in featured_products %}
                <div class="col-6 col-md-4 col-lg-3">
                    <div class="card">
                        <a href="{% url 'product' product.prod_id %}">
                            {% if product.prod_img %}
                                <img class="card-img-top" src="{{ product.prod_img.url }}">
                            {% else %}
                                <img class="card-img-top" src="{% static 'BookFair/img/product/placeholder.webp' %}">
                            {% endif %}
                            <div class="card-body">
                                <span class="badge bg-primary-subtle text-uppercase">{{ product.cat.cat_name }}</span>
                                <p class="fs-3 mt-1 mb-0 lh-sm">{{ product.prod_name }}</p>
                                <p class="fs-5">${{ product.prod_price }}</p>
                            </div>
                        </a>
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    </div>
</div>
{% endblock %}

BookFair/templates/BookFair/login.html
{% extends "base.html" %}

{% block title %} Login {% endblock %}

{% load bootstrap5 %}
{% load bootstrap_icons %}

{% block content %}

{% if user.is_authenticated %}
<div class="container mb-5">
    <div class="col-12 d-flex justify-content-center align-items-center gap-3 mt-5">
        {% bs_icon 'person-check-fill' color='#6c757d' size='4em' %}
        <span class="fs-1 text-secondary">You're already signed in!</span>
    </div>
    <div class="col-12 d-flex justify-content-center align-items-center gap-3 mt-5">
        <p class="fs-4 text-secondary">
            Find your profile <a href="{% url 'profile' %}">here.</a>
        </p>
    </div>
</div>
{% else %}
<div class="container mt-3 mb-0">
    <h1>Log in</h1>
</div>
<div class="container mb-5">
<hr>
    <div class="row">
        <!-- Display message upon successful/unsuccessful signup here -->
        {% if messages %}
            {% for message in messages %}
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                    <div class="alert alert-danger" role="alert">
                        {{ message }}
                    </div>                              
                {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                    <div class="alert alert-success" role="alert">
                        {{ message }}
                    </div>
                {% else %}
                    <div class="alert alert-primary" role="alert">
                        {{ message }}
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
        <form class="row g-3 mt-0 px-5" method="post">
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-primary btn-block">Log in</button>
        </form>
    </div>
    <div class="row">
        <div class="col-12 p-5">
            <p>No account? <a href="{% url 'signup' %}">Sign up!</a></p>
        </div>
    </div>
</div>
{% endif %}

{% endblock %}

BookFair/templates/BookFair/logout.html
{% extends "base.html" %}

{% block title %} Logged out {% endblock %}

{% load bootstrap5 %}
{% load bootstrap_icons %}

{% block content %}

<div class="row">
    <div class="col-12 d-flex justify-content-center align-items-center gap-3 mt-5">
        {% bs_icon 'door-closed' color='#6c757d' size='4em' %}
        <span class="fs-1 text-secondary">You've been signed out!</span>
    </div>
    <div class="col-12 d-flex justify-content-center align-items-center gap-3 mt-5">
        <p class="fs-4 text-secondary">
            If you'd like to sign back in, <a href="{% url 'login' %}">log in here.</a>
        <br>
            If you arrived at this page by accident, you'll have to sign in again.
        <br>
            If you don't have an account, <a href="{% url 'signup' %}">you can sign up here.</a>
        </p>
    </div>
</div>

{% endblock %}

BookFair/templates/BookFair/product.html
{% extends "base.html" %}
<!-- Title -->
{% block title %} eBookFair | {{ product.prod_name }} {% endblock %}
<!-- Load django apps -->
{% load static %}
{% load bootstrap5 %}
{% load bootstrap_icons %}
<!-- Start block -->
{% block content %}
<!-- Product CSS -->
<link rel="stylesheet" type="text/css" href="{% static 'BookFair/css/product.css' %}">
<!-- Product page container -->
<div class="container my-5">
    {% if product %}
    <div class="card product-card-full mx-auto">
        <div class="row no-gutters">
            <div class="col-md-6">
                {% if product.prod_img %}
                    <img src="{{ product.prod_img.url }}" class="card-img product-image" alt="Product Image">
                {% else %}
                    <img src="{% static 'BookFair/img/product/placeholder.webp' %}" class="card-img product-image" alt="Placeholder product image">
                {% endif %}
            </div>
            <div class="col-md-6">
                <div class="card-body mb-5">
                    <h2 class="card-title mt-4 mb-3">{{ product.prod_name }}</h2>
                    <span class="badge bg-primary-subtle text-uppercase mb-2">{{ product.cat.cat_name }}</span>
                    <p class="card-text">{{ product.prod_descript }}</p>
                    <p><strong>Price: </strong>${{ product.prod_price }}</p>
                    <!-- Check in stock -->
                    {% if product.prod_stock > 0 %}
                        <button class="btn bg-primary text-light btn-block">
                            {% bs_icon 'cart-plus-fill' color='white' size='1.25em' %}
                            Add to Cart
                        </button>
                        <p class="card-text mt-3">Only <span class="fw-bold">{{ product.prod_stock }}</span> in stock!</p>
                    {% else %}
                        <button class="btn btn-secondary text-light btn-block" disabled>
                            {% bs_icon 'cart-x-fill' color='white' size='1.25em' %}
                            Out of stock
                        </button>
                        <p class="card-text mt-3">No stock available :&#40; Check back soon!</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}

BookFair/templates/BookFair/profile.html
{% extends "base.html" %}

{% block title %} My profile {% endblock %}

{% load bootstrap5 %}
{% load bootstrap_icons %}

{% block content %}

{% if messages %}
    {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            <div class="alert alert-danger" role="alert">
                {{ message }}
            </div>                              
        {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            <div class="alert alert-success" role="alert">
                {{ message }}
            </div>
        {% else %}
            <div class="alert alert-primary" role="alert">
                {{ message }}
            </div>
        {% endif %}
    {% endfor %}
{% endif %}
<div class="row">
{% if user.is_authenticated %}
    <div class="col-md-6 offset-md-3 profile-info">
        <div class="card">
            <div class="card-header">
                Profile
            </div>
            <div class="card-body">
                <h3 class="card-title">{{ user.username }}</h3>
                <h4 class="card-subtitle">{{ user.email }}</h4>
                <a href="{% url 'logout' %}">
                    <button type="button" class="mt-3 btn btn-outline-danger">Sign out</button>
                </a>
            </div>
            {% if customer %}
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Name: {{ customer.cus_fname }} {{ customer.cus_initial }} {{ customer.cus_lname }}</li>
                <li class="list-group-item">Phone: +{{ customer.cus_phone_country }} {{ customer.cus_phone }}</li>
            </ul>
            {% endif %}
        </div>
    </div>
{% else %}
    <div class="col-12 d-flex justify-content-center align-items-center gap-3 mt-5">
        {% bs_icon 'emoji-frown-fill' color='#6c757d' size='4em' %}
        <span class="fs-1 text-secondary">You're not signed in!</span>
    </div>
    <div class="col-12 d-flex justify-content-center align-items-center gap-3 mt-5">
        <p class="fs-4 text-secondary">
            If you have an account, <a href="{% url 'login' %}">log in here.</a>
        <br>
            If you would like to register, <a href="{% url 'signup' %}">sign up for an account here.</a>
        </p>
    </div>
{% endif %}
</div>
{% endblock %}

BookFair/templates/BookFair/signup.html
{% extends "base.html" %}

{% block title %} Sign up for an account {% endblock %}

{% load bootstrap5 %}
{% load bootstrap_icons %}

{% block content %}

<div class="row">
{% if user.is_authenticated %}
    <div class="col-12 d-flex justify-content-center align-items-center gap-3 mt-5">
        {% bs_icon 'person-check-fill' color='#6c757d' size='4em' %}
        <span class="fs-1 text-secondary">You're already signed in!</span>
    </div>
    <div class="col-12 d-flex justify-content-center align-items-center gap-3 mt-5">
        <p class="fs-4 text-secondary">
            Find your profile <a href="{% url 'profile' %}">here.</a>
        </p>
    </div>
{% else %}
    <!-- Display message upon successful/unsuccessful signup here -->
    {% if messages %}
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <div class="alert alert-danger" role="alert">
                    {{ message }}
                </div>                              
            {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                <div class="alert alert-success" role="alert">
                    {{ message }}
                </div>
            {% else %}
                <div class="alert alert-primary" role="alert">
                    {{ message }}
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
    <div class="col-md-6 offset-md-3 login-form">
        <h2 class="text-center">Sign up</h2>
        <form class="row g-3" method="post" action="{% url 'signup' %}">
            {% csrf_token %}
            <h3>Sign-in details</h3>
            <p class="my-0">
                You'll use these details to log into your account.
            </p>
            <div class="col-12">
                <label for="id_username" class="form-label">{{ form.username.label }}</label>
                {{ form.username }}
            </div>
            <div class="col-md-6">
                <label for="id_password1" class="form-label">{{ form.password1.label }}</label>
                {{ form.password1 }}
            </div>
            <div class="col-md-6">
                <label for="id_password2" class="form-label">{{ form.password2.label }}</label>
                {{ form.password2 }}
            </div>
            <hr>
            <h3>Personal details</h3>
            <p class="my-0">
                You'll use these details in your orders.
            </p>
            <div class="col-5">
                <label for="id_first_name" class="form-label">{{ form.first_name.label }}</label>
                {{ form.first_name }}
            </div>
            <div class="col-2">
                <label for="id_initial_name" class="form-label">{{ form.initial_name.label }}</label>
                {{ form.initial_name }}
            </div>
            <div class="col-5">
                <label for="id_last_name" class="form-label">{{ form.last_name.label }}</label>
                {{ form.last_name }}
            </div>
            <div class="col-12">
                <label for="id_email" class="form-label">{{ form.email.label }}</label>
                {{ form.email }}
            </div>
            <div class="col-4">
                <label for="id_phone_country" class="form-label">{{ form.phone_country.label }}</label>
                <div class="input-group">
                    <span class="input-group-text">+</span>
                    {{ form.phone_country }}
                </div>
            </div>
            <div class="col-8">
                <label for="id_phone_number" class="form-label">{{ form.phone_number.label }}</label>
                {{ form.phone_number }}
            </div>
            <button type="submit" class="btn btn-primary btn-block">Sign up</button>
        </form>
    </div>
{% endif %}
</div>
{% endblock %}